### ISSUE TITLE
Add Full Tailwind Color Palette? 

### ISSUE THREAD

**Issue by sebmellen** [agcty/nextjs-advanced-starter#10]
Since the Tailwind file is purged in production, I think it may be useful to make all of the Tailwind color variants available by default. This dramatically increases the bundle size, but this increase is essentially irrelevant to the end user and to the published site with Tailwind JIT speeds and PurgeCSS.

You can take a look at this gist: https://gist.github.com/sebmellen/e939ce8a29fd6cb611ef6f283f700f2c for an idea of what that tailwind.config.js looks like.

Let me know your thoughts!

**Comment by agcty** [comment]
Thanks again for your comment! Tailwind implicitly comes with the full color palette anyways, you don't need to explicitly add the default tailwind colors to be able to use them. However, if you do want to override them and and new ones you can always extend it!

**Comment by sebmellen** [comment]
Hmm, I don't think that's the case without importing tailwindcss/colors like so: `const colors = require('tailwindcss/colors')` in the `tailwind.config.js` file. It's true that the default color palette is available, but it's definitely required to add the declarations for colors _not_ in the default list.

The colors in the default list are as follows:

- Gray
- Red
- Yellow
- Green (actually Emerald) [1]
- Blue
- Indigo
- Purple
- Pink

Whereas the full list of colors is [2]:

- Blue Gray
- Cool Gray
- Gray
- True Gray
- Warm Gray
- Red
- Orange
- Amber
- Yellow
- Lime
- Green
- Emerald
- Teal
- Cyan
- Light Blue
- Blue
- Indigo
- Violet
- Purple
- Fuchsia
- Pink

A fair number of themes and prebuilt designs use colors that are only available in the full palette. These colors are not included in the default palette, and therefore show up as transparent or simply unstyled if the user doesn't explicitly declare them. This can be confusing, especially for users who are just starting out with Tailwind.

Personally I feel this is a deficiency with the Tailwind documentation, because they don't add an easy copy-paste-able `tailwind.config.js` example with all the colors declared. But I think full color palette support would be a useful feature to have in this starter!

Anyway, I totally understand if you don't feel that this is important — it's your repo after all :).


[1]: https://tailwindcss.com/docs/customizing-colors  
[2]: https://tailwindcss.com/docs/customizing-colors#color-palette-reference
