### ISSUE TITLE
Command line option

### ISSUE THREAD

**Issue by sicktastic** [agcty/nextjs-advanced-starter#12]
Trying out your template, because I love all the tools that you implemented and I end up adding them to my Next.js projects.   This a feature request perhaps, it would be nice to create a project with some sort of a command:

`nextstarter projectname --something --something`

Similar to [suspender](https://github.com/thoughtbot/suspenders) project for Rails.

In any case, thanks for creating this.

**Comment by agcty** [comment]
Thanks for your valuable feedback! I think an npx command would be the easiest way of achieving this. Will definitely consider this in the future, but for now, I'll just leave this feature request open and if someone else wants this implemented they can just comment "+1" 🙌
