### ISSUE TITLE
warn  - Disabled SWC as replacement for Babel because of custom Babel configuration

### ISSUE THREAD

**Issue by RebootGG** [agcty/nextjs-advanced-starter#28]
Hi, 

There is the following warning in the console : 
`warn  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled`

A simple solution would be to remove the `.babelrc` file and add the following code in the `jest.config.js` file : 
```
// ...
transform: {
    "^.+\\.(js|jsx|ts|tsx)$": ["babel-jest", { presets: ["next/babel"] }],
  },
// ...

```

[Original source](https://github.com/vercel/next.js/issues/30811#issuecomment-963102661 
)

If I'm not mistaken, this would allow to use SWC instead of Babel, thus to improve the performances while removing the warning message from the console.

I can submit a PR if you'd like.

BTW, thanks for the template, it is clean and much appreciated 👍

**Comment by dharmveer97** [comment]
can you please share full file code its now working for me

In my old project 

filename:- .babelrc
{
  "presets": ["next/babel"],
  "plugins": [["styled-components", { "ssr": true }]]
}


warn  - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled

**Comment by dharmveer97** [comment]
> Hi,
> 
> There is the following warning in the console : `warn - Disabled SWC as replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled`
> 
> A simple solution would be to remove the `.babelrc` file and add the following code in the `jest.config.js` file :
> 
> ```
> // ...
> transform: {
>     "^.+\\.(js|jsx|ts|tsx)$": ["babel-jest", { presets: ["next/babel"] }],
>   },
> // ...
> ```
> 
> [Original source](https://github.com/vercel/next.js/issues/30811#issuecomment-963102661)
> 
> If I'm not mistaken, this would allow to use SWC instead of Babel, thus to improve the performances while removing the warning message from the console.
> 
> I can submit a PR if you'd like.
> 
> BTW, thanks for the template, it is clean and much appreciated 👍



Could you please share the full file code it's not working for me.

In my old project 

filename:- .babelrc
{
  "presets": ["next/babel"],
  "plugins": [["styled-components", { "ssr": true }]]
}

Now I'm in latest version 

warn  - Disabled SWC as a replacement for Babel because of custom Babel configuration ".babelrc" https://nextjs.org/docs/messages/swc-disabled

**Comment by RebootGG** [comment]
Hi, 

Here is my `jest.config.js` file : 

```
module.exports = {
  collectCoverageFrom: ['**/*.{js,jsx,ts,tsx}', '!**/*.d.ts', '!**/node_modules/**'],
  moduleNameMapper: {
    // Handle CSS imports (with CSS modules)
    '^.+\\.module\\.(css|sass|scss)$': 'identity-obj-proxy',

    // Handle CSS imports (without CSS modules)
    // '^.+\\.(css|sass|scss)$': '<rootDir>/__mocks__/styleMock.js',

    // Handle image imports
    '^.+\\.(jpg|jpeg|png|gif|webp|avif|svg)$': `<rootDir>/__mocks__/fileMock.js`,

    // Handle module aliases
    '^@components(.*)$': '<rootDir>/src/components$1',
  },
  setupFilesAfterEnv: ['<rootDir>/jest.setup.tsx'],
  testPathIgnorePatterns: ['<rootDir>/node_modules/', '<rootDir>/.next/'],
  transform: {
    // Use babel-jest to transpile tests with the next/babel preset
    '^.+\\.(js|jsx|ts|tsx)$': ['babel-jest', { presets: ['next/babel'] }],
  },
  transformIgnorePatterns: ['/node_modules/', '^.+\\.module\\.(css|sass|scss)$'],
};

```

Also, I have deleted the `.babelrc` file at the root of my project

**Comment by agcty** [comment]
Have removed the default babel config file to opt in to swc, much faster builds already!
Also just upgraded the template to tailwind 3
